receivers:
  otlp:
    protocols:
      grpc:
      http: 

exporters:
  otlp:
    endpoint: quickwit:7281
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

# connectors:
#   spanmetrics:
#     dimensions:
#       - name: http.method
#       - name: http.status_code
#       - name: http.route

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    # metrics/spanmetrics:
    #   receivers: [spanmetrics]
    #   exporters: [prometheus]
