# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Loki
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - uid: prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    url: http://prometheus:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
    readOnly: false
    editable: true
  - uid: quickwit
    orgId: 1
    name: Quickwit
    type: quickwit-quickwit-datasource
    readOnly: false
    url: http://quickwit:7280/api/v1
    jsonData:
      index: 'otel-traces-v0_7'
      timeField: span_start_timestamp_nanos
      logMessageField: service_name,span_name
      logLevelField: ""
      dataLinks:
        - datasourceUid: jaeger
          field: trace_id
          url: '$${__value.raw}'
  - uid: jaeger
    orgId: 1
    name: Jaeger
    type: jaeger
    readOnly: false
    url: http://quickwit:7280/api/v1/otel-traces-v0_7/jaeger
    jsonData:
      tracesToLogsV2:
        # Field with an internal link pointing to a logs data source in Grafana.
        # datasourceUid value must match the uid value of the logs data source.
        datasourceUid: 'quickwit'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        filterByTraceID: true
        filterBySpanID: true
        customQuery: true
        query: 'method="${__span.tags.method}"'
